# See https://developer.github.com/v3/repos/#edit for all available settings.
repository:
  name: frontend-skeleton
  description: Frontend skeleton 
  default_branch: main
  private: true

  has_issues: false
  has_wiki: false
  has_downloads: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - 'build'
          - 'lint'
          - 'test'
